name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node: [20]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - run: sudo npm i -g @yao-pkg/pkg
      - run: pnpm install --frozen-lockfile

      - name: Set up QEMU
        run: |
          sudo apt-get update
          sudo apt-get install --reinstall -y qemu-user-static

      - name: Install ldid
        run: |
          sudo wget https://github.com/jesec/ldid-static/releases/download/v2.1.4/ldid-amd64 -O /usr/local/bin/ldid
          sudo chmod +x /usr/local/bin/ldid

      - run: npm run build-pkg
      - run: git fetch origin ${{ github.ref }}
      - run: git for-each-ref ${{ github.ref }} --format="%(contents)" > body

      - name: Rename linuxstatic to linux
        run: |
          mv dist-pkg/flood-linuxstatic-x64 dist-pkg/flood-linux-x64

      - name: Get the version
        id: get_version
        run: echo VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body_path: body
          files: |
            dist-pkg/flood-linux-x64
